// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifpmhvxnqxzecdeeobjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmcG1odnhucXh6ZWNkZWVvYmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTA0MzAsImV4cCI6MjA3MTEyNjQzMH0.IuSZICLQ49zbbKBnn5Ow-iIJFofhCtrRs0NF5c2xKeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});